// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using web_api_personas;

#nullable disable

namespace web_api_personas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("web_api_personas.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("web_api_personas.Entidades.CategoriaPersona", b =>
                {
                    b.Property<int>("categoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("personaId")
                        .HasColumnType("integer");

                    b.HasKey("categoriaId", "personaId");

                    b.HasIndex("personaId");

                    b.ToTable("CategoriaPersonas");
                });

            modelBuilder.Entity("web_api_personas.Entidades.Correo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<string>("correos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Correos");
                });

            modelBuilder.Entity("web_api_personas.Entidades.Dirreccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codigopostal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo")
                        .HasColumnType("text");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Dirrecciones");
                });

            modelBuilder.Entity("web_api_personas.Entidades.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorreoId")
                        .HasColumnType("integer");

                    b.Property<int>("DirreccionId")
                        .HasColumnType("integer");

                    b.Property<int>("TelefonoId")
                        .HasColumnType("integer");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("cedula")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("fechanacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorreoId");

                    b.HasIndex("DirreccionId");

                    b.HasIndex("TelefonoId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("web_api_personas.Entidades.Telefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<string>("codigopais")
                        .HasColumnType("text");

                    b.Property<int>("numero")
                        .HasColumnType("integer");

                    b.Property<string>("tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Telefonos");
                });

            modelBuilder.Entity("web_api_personas.Entidades.CategoriaPersona", b =>
                {
                    b.HasOne("web_api_personas.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_api_personas.Entidades.Persona", "Persona")
                        .WithMany("CategoriaPersonas")
                        .HasForeignKey("personaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("web_api_personas.Entidades.Correo", b =>
                {
                    b.HasOne("web_api_personas.Entidades.Persona", null)
                        .WithMany("Correos")
                        .HasForeignKey("PersonaId");
                });

            modelBuilder.Entity("web_api_personas.Entidades.Dirreccion", b =>
                {
                    b.HasOne("web_api_personas.Entidades.Persona", null)
                        .WithMany("Dirreciones")
                        .HasForeignKey("PersonaId");
                });

            modelBuilder.Entity("web_api_personas.Entidades.Persona", b =>
                {
                    b.HasOne("web_api_personas.Entidades.Correo", "Correo")
                        .WithMany()
                        .HasForeignKey("CorreoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_api_personas.Entidades.Dirreccion", "Dirreccion")
                        .WithMany()
                        .HasForeignKey("DirreccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web_api_personas.Entidades.Telefono", "Telefono")
                        .WithMany()
                        .HasForeignKey("TelefonoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Correo");

                    b.Navigation("Dirreccion");

                    b.Navigation("Telefono");
                });

            modelBuilder.Entity("web_api_personas.Entidades.Telefono", b =>
                {
                    b.HasOne("web_api_personas.Entidades.Persona", null)
                        .WithMany("Telefonos")
                        .HasForeignKey("PersonaId");
                });

            modelBuilder.Entity("web_api_personas.Entidades.Persona", b =>
                {
                    b.Navigation("CategoriaPersonas");

                    b.Navigation("Correos");

                    b.Navigation("Dirreciones");

                    b.Navigation("Telefonos");
                });
#pragma warning restore 612, 618
        }
    }
}
